workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          pod install --repo-update || true
      - name: Build app
        script: |
          xcodebuild \
            -project "DurakAI.xcodeproj" \
            -scheme "DurakAI" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Build/DurakAI.xcarchive \
            archive
      - name: Export ipa
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/Build/DurakAI.xcarchive \
            -exportPath $CM_BUILD_DIR/Build/ipa \
            -exportOptionsPlist /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/Build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
